### ISSUE TITLE
CHESS BOARD

### ISSUE THREAD

**Issue by Salto7B** [7dpk/OpenCV-Chess-Bot#1]
it worked on chess.com and all chess boards but i cant make it work at this board
![Screenshot_2](https://user-images.githubusercontent.com/100636745/235561041-7f815f60-8441-4aa3-96ce-3fd2a8c4511b.png)
![Screenshot_1](https://user-images.githubusercontent.com/100636745/235561047-ec415e33-122d-44fb-9798-03111a193086.png)

**Comment by 7dpk** [comment]
Can you give me a some more details as of where and how this happened, did it errored at the start or during the gameplay. 
Which platform are you using Linux/Windows?
Did the bot correctly recognize the board?
Answering these questions will greatly help me to pinpoint the problem.
Thanks for trying it out :)

**Comment by Salto7B** [comment]
> Can you give me a some more details as of where and how this happened, did it errored at the start or during the gameplay. Which platform are you using Linux/Windows? Did the bot correctly recognize the board? Answering these questions will greatly help me to pinpoint the problem. Thanks for trying it out :)

the problem is the bot didn't recognize the board but if i tried the bot on ches.com or lichess it work perfect i think its because the chess theme but the problem i cant change it
u can try to open this image and start the bot i tried it with chess.com image and the bot started he will try to move the pieces in the image
i am on win 10

**Comment by 7dpk** [comment]
Can you share me a screenshot with the chessboard in it, I guess there might be some issue with the contrast, which might need some parameter tweaking.

**Comment by Salto7B** [comment]
> Can you share me a screenshot with the chessboard in it, I guess there might be some issue with the contrast, which might need some parameter tweaking.

sure here is it
![Screenshot_4](https://user-images.githubusercontent.com/100636745/235728380-e9491518-a2b9-4a8a-912a-ac3c73f5df19.png)
